### ISSUE TITLE
Internationalization aka i18n

### ISSUE THREAD

**Issue by wal0x** [cgross/angular-busy#104]
It will be great if we can change the language of the "please wait..." from a parameter given to directive.

**Comment by baumannzone** [comment]
Did you get a solution for this?

**Comment by wal0x** [comment]
Yes, well I am using a angular library for i18n so to chnage the message just give the string wanted to "message:", in the example below I give my string to a filter that do the translating job:

cg-busy="{promise:importingPromise,message: ('PLEASE_WAIT' | translate)}"
