### ISSUE TITLE
Does the component work with a native Promise?

### ISSUE THREAD

**Issue by stanleyxu2005** [cgross/angular-busy#114]
My simple does not work. I dont want to use Angular's promise.
```
<div cg-busy="loading">Something</div>
```
In my controller
```
$scope.loading = new Promise(function(resolve, reject) {
  setTimetout(function() {
    resolve();
  }, 3000);
));
```
My question is how to fix my problem?

**Comment by MarkMYoung** [comment]
It will.  The code checks to see whether the first truthy property of `promiseThing && (promiseThing.then || promiseThing.$then || (promiseThing.$promise && promiseThing.$promise.then` is not `undefined`.
