### ISSUE TITLE
Overriding default values not working

### ISSUE THREAD

**Issue by morfin** [cgross/angular-busy#79]
This is how I'm trying to override value, but I still getting "Please Wait...". 

What am I doing wrong ?

```
angular.module('app').run(function(){
     angular.module('app').value('cgBusyDefaults',{
            message: 'Loading...'
        });
));
```

What is happening is that cgBusy injects the default value:
```
angular.module('cgBusy').value('cgBusyDefaults',{});
```

Instead of the value I defined. Looks like mine does not exist when the directive is called.

Any idea?

**Comment by muzuro** [comment]
Hi, i have same issue. What was solution of problem?

**Comment by morfin** [comment]
Solution was:

```
angular.module('app').run(function(cgBusyDefaults){
    cgBusyDefaults.message= 'Your message here';
    ....
});

```
