### ISSUE TITLE
Publish newsest version to npm

### ISSUE THREAD

**Issue by sebald** [cgross/angular-busy#80]
Please `npm publish` version 1.4.3! It is only available via bower or directly via git. Thanks!

**Comment by axelson** [comment]
+1

**Comment by swaniris** [comment]
+1

**Comment by sondreb** [comment]
:+1: +1

**Comment by kencaron** [comment]
+1

**Comment by mgobbi-tecnom** [comment]
+1

**Comment by brunnurs** [comment]
+1

**Comment by heivoll** [comment]
+1

**Comment by cube5** [comment]
+1

**Comment by mxlle** [comment]
+2

**Comment by streetcore** [comment]
+1

**Comment by beatelite** [comment]
+1

**Comment by brunnurs** [comment]
@cgross is there a plan to release the library for npm and continue developing (e.g. #92)? 

@everyone waiting for an npm-release: I use a fork of this library (https://github.com/myflowpl/angular-busy2) which has been released to npm a few months ago (https://www.npmjs.com/package/angular-busy2) and is also supporting the CommonJS-standard. I'd rather use the original, but there is not much activity in this repo...

**Comment by PitBeast** [comment]
Published

**Comment by brunnurs** [comment]
Thx @PitBeast

**Comment by stephengardner** [comment]
Oh man, this was back in February!  That fork works.  Guess this repo is dead 😢
